const TIER_ORDER = { free: 0, silver: 1, gold: 2, platinum: 3, none: 0 };
const RARITY_ORDER = { common: 0, rare: 1, epic: 2, legendary: 3 };

const DEFAULT_PACK_PROFILES = {
  silver: {
    name: "Silver Pack",
    description: "A polished starter pack with guaranteed rare-tier loot and a rising chance of epic hits.",
    image: "🥈",
    headline: "Guaranteed Rare • Epic pity after 4 opens",
    pointsCost: 180,
    tierRequired: "free",
    guaranteedRarity: "rare",
    animationTheme: "silver",
    pityEpicThreshold: 4,
    pityLegendaryThreshold: 16,
    bonusMultiplier: 1.02,
    featured: true,
    drops: [
      { type: "points", rarity: "rare", weight: 42, pointsAmount: 90, label: "90 Points", revealText: "Clean pull. Stack the points." },
      { type: "points", rarity: "rare", weight: 28, pointsAmount: 150, label: "150 Points", revealText: "Strong silver payout." },
      { type: "coupon", rarity: "rare", weight: 18, discountPercent: 8, label: "8% Store Coupon", revealText: "A useful discount enters the club." },
      { type: "coupon", rarity: "epic", weight: 7, discountPercent: 18, label: "18% Store Coupon", revealText: "Epic flare. Big savings unlocked." },
      { type: "gift_card", rarity: "epic", weight: 4, discountAmount: 5, label: "€5 Gift Card", revealText: "Silver just turned premium." },
      { type: "points", rarity: "legendary", weight: 1, pointsAmount: 1200, label: "Legendary 1200 Points", revealText: "Jackpot. The tunnel explodes in silver light." },
    ],
  },
  gold: {
    name: "Gold Pack",
    description: "Elite drop rates, heavier jackpots, and a much faster path toward legendary reveals.",
    image: "🥇",
    headline: "Guaranteed Epic • Legendary pity after 7 opens",
    pointsCost: 420,
    tierRequired: "silver",
    guaranteedRarity: "epic",
    animationTheme: "gold",
    pityEpicThreshold: 1,
    pityLegendaryThreshold: 7,
    bonusMultiplier: 1.08,
    featured: true,
    drops: [
      { type: "points", rarity: "epic", weight: 32, pointsAmount: 320, label: "320 Points", revealText: "Gold pack, gold return." },
      { type: "points", rarity: "epic", weight: 25, pointsAmount: 480, label: "480 Points", revealText: "A big epic surge." },
      { type: "coupon", rarity: "epic", weight: 18, discountPercent: 22, label: "22% Store Coupon", revealText: "This is a serious coupon." },
      { type: "gift_card", rarity: "epic", weight: 12, discountAmount: 10, label: "€10 Gift Card", revealText: "Gold-tier value secured." },
      { type: "coupon", rarity: "legendary", weight: 8, discountPercent: 40, label: "40% Store Coupon", revealText: "Legendary discount. Massive value." },
      { type: "points", rarity: "legendary", weight: 5, pointsAmount: 3000, label: "Legendary 3000 Points", revealText: "The stadium erupts. Monster point haul." },
    ],
  },
  platinum: {
    name: "Platinum Pack",
    description: "Endgame pack energy. Premium odds, cinematic reveals, and the best jackpot ceiling in the system.",
    image: "💎",
    headline: "Guaranteed Epic • Legendary pity after 4 opens",
    pointsCost: 900,
    tierRequired: "platinum",
    guaranteedRarity: "epic",
    animationTheme: "platinum",
    pityEpicThreshold: 1,
    pityLegendaryThreshold: 4,
    bonusMultiplier: 1.15,
    featured: true,
    drops: [
      { type: "points", rarity: "epic", weight: 30, pointsAmount: 650, label: "650 Points", revealText: "Platinum points flood in." },
      { type: "coupon", rarity: "epic", weight: 22, discountPercent: 30, label: "30% Store Coupon", revealText: "High-end coupon, instant impact." },
      { type: "gift_card", rarity: "legendary", weight: 18, discountAmount: 20, label: "€20 Gift Card", revealText: "Legendary card. Premium pull." },
      { type: "coupon", rarity: "legendary", weight: 14, discountPercent: 50, label: "50% Store Coupon", revealText: "Half-price destruction." },
      { type: "points", rarity: "legendary", weight: 11, pointsAmount: 5000, label: "Legendary 5000 Points", revealText: "Platinum jackpot. Unreal hit." },
      { type: "gift_card", rarity: "legendary", weight: 5, discountAmount: 50, label: "€50 Gift Card", revealText: "Top-board reward. Absolute scenes." },
    ],
  },
};

function normalizePackClass(pack) {
  if (pack.packClass && DEFAULT_PACK_PROFILES[pack.packClass]) {
    return pack.packClass;
  }

  const normalizedName = (pack.name || "").toLowerCase();
  if (normalizedName.includes("platinum")) return "platinum";
  if (normalizedName.includes("gold")) return "gold";
  return "silver";
}

const DEFAULT_QUEST_CATALOG = [
  {
    questKey: "starter_contract_verified",
    title: "Starter Contract",
    description: "Verify your account and receive your starter points.",
    type: "signup_welcome",
    rewardPoints: 75,
    icon: "🚀",
    category: "onboarding",
    sortOrder: 1,
    cooldownHours: 0,
    completionLimit: 1,
    validationRules: { requireVerifiedEmail: true },
    metadata: { target: 1 },
  },
  {
    questKey: "invite_friend_link",
    title: "Invite a Friend",
    description: "Invite 1 friend with your referral link.",
    type: "referral_invite",
    rewardPoints: 180,
    icon: "🔗",
    category: "career",
    sortOrder: 2,
    cooldownHours: 0,
    completionLimit: 1,
    metadata: { targetReferrals: 1, referralPath: "/register" },
  },
  {
    questKey: "profile_setup",
    title: "Squad Setup",
    description: "Complete your profile (username, email, and phone).",
    type: "complete_profile",
    rewardPoints: 80,
    icon: "👤",
    category: "onboarding",
    sortOrder: 3,
    cooldownHours: 0,
    completionLimit: 1,
  },
  {
    questKey: "first_purchase_contract",
    title: "First Whistle Purchase",
    description: "Complete your first paid order.",
    type: "first_purchase",
    rewardPoints: 120,
    icon: "🛍️",
    category: "career",
    sortOrder: 4,
    cooldownHours: 0,
    completionLimit: 1,
  },
  {
    questKey: "seven_day_form",
    title: "Form Streak",
    description: "Reach a 7-day login streak.",
    type: "streak_login",
    rewardPoints: 140,
    icon: "🔥",
    category: "weekly",
    sortOrder: 5,
    cooldownHours: 168,
    completionLimit: 52,
    metadata: { requiredDays: 7 },
  },
  {
    questKey: "weekly_two_orders",
    title: "Weekend Warrior",
    description: "Place 2 paid orders within 7 days.",
    type: "weekly_orders",
    rewardPoints: 160,
    icon: "🧾",
    category: "weekly",
    sortOrder: 6,
    cooldownHours: 168,
    completionLimit: 52,
    metadata: { requiredOrders: 2 },
  },
  {
    questKey: "order_milestone_five",
    title: "League Matches (Total)",
    description: "Complete 5 paid orders in total.",
    type: "order_milestone",
    rewardPoints: 210,
    icon: "🎯",
    category: "career",
    sortOrder: 7,
    cooldownHours: 0,
    completionLimit: 1,
    metadata: { targetOrders: 5 },
  },
  {
    questKey: "pack_open_master",
    title: "Pack Opener",
    description: "Open 3 reward packs.",
    type: "pack_open_total",
    rewardPoints: 130,
    icon: "📦",
    category: "career",
    sortOrder: 8,
    cooldownHours: 0,
    completionLimit: 1,
    metadata: { targetPacks: 3 },
  },
  {
    questKey: "season_budget_80",
    title: "Season Budget Boss",
    description: "Spend 80 EUR in paid orders this month.",
    type: "monthly_spend",
    rewardPoints: 250,
    icon: "💰",
    category: "seasonal",
    sortOrder: 9,
    cooldownHours: 720,
    completionLimit: 12,
    metadata: { targetSpend: 80, currency: "EUR" },
  },
  {
    questKey: "reward_redeemer",
    title: "Reward Collector",
    description: "Redeem 2 rewards from the shop.",
    type: "redeem_total",
    rewardPoints: 140,
    icon: "🎁",
    category: "career",
    sortOrder: 10,
    cooldownHours: 0,
    completionLimit: 1,
    metadata: { targetRedemptions: 2 },
  },
  {
    questKey: "career_points_1500",
    title: "Grinding Legend",
    description: "Earn 1500 lifetime points.",
    type: "points_earned",
    rewardPoints: 220,
    icon: "🏅",
    category: "career",
    sortOrder: 11,
    cooldownHours: 0,
    completionLimit: 1,
    metadata: { targetPoints: 1500 },
  },
  {
    questKey: "community_follow_soon",
    title: "Community Scout",
    description: "Follow our social channels to unlock this objective soon.",
    type: "social_follow",
    rewardPoints: 40,
    icon: "📣",
    category: "seasonal",
    featureFlag: false,
    sortOrder: 12,
    cooldownHours: 0,
    completionLimit: 1,
  },
];

module.exports = {
  TIER_ORDER,
  RARITY_ORDER,
  DEFAULT_PACK_PROFILES,
  DEFAULT_QUEST_CATALOG,
  normalizePackClass,
};
